/* Automatically generated.  Do not edit */
/* See the mkopcodeh.awk script for details */
#define OP_ReadCookie                  1
#define OP_AutoCommit                  2
#define OP_Found                       3
#define OP_NullRow                     4
#define OP_Lt                          70
#define OP_MoveLe                      5
#define OP_Variable                    6
#define OP_Pull                        7
#define OP_Sort                        8
#define OP_SortNext                    9
#define OP_IfNot                       10
#define OP_Gosub                       11
#define OP_Add                         76
#define OP_NotFound                    12
#define OP_IsNull                      64
#define OP_MoveLt                      13
#define OP_Push                        14
#define OP_CreateIndex                 15
#define OP_Statement                   16
#define OP_Callback                    17
#define OP_MemLoad                     18
#define OP_DropIndex                   19
#define OP_Next                        20
#define OP_SetNumColumns               21
#define OP_Ge                          71
#define OP_BitNot                      84
#define OP_Dup                         22
#define OP_Rewind                      23
#define OP_Multiply                    78
#define OP_AggFunc                     24
#define OP_Gt                          68
#define OP_Last                        25
#define OP_MustBeInt                   26
#define OP_Ne                          66
#define OP_MoveGe                      27
#define OP_AggSet                      28
#define OP_ListRewind                  29
#define OP_String                      30
#define OP_ForceInt                    31
#define OP_Close                       32
#define OP_Recno                       33
#define OP_AggFocus                    34
#define OP_AbsValue                    35
#define OP_RowData                     36
#define OP_BitOr                       73
#define OP_NotNull                     65
#define OP_MoveGt                      37
#define OP_Not                         60
#define OP_OpenPseudo                  38
#define OP_Halt                        39
#define OP_Real                        122
#define OP_IdxLT                       40
#define OP_PutIntKey                   41
#define OP_Distinct                    42
#define OP_SortReset                   43
#define OP_AggReset                    44
#define OP_Function                    45
#define OP_IntegrityCk                 46
#define OP_Remainder                   80
#define OP_HexBlob                     123
#define OP_ShiftLeft                   74
#define OP_BitAnd                      72
#define OP_Or                          58
#define OP_NotExists                   47
#define OP_MemStore                    48
#define OP_IdxDelete                   49
#define OP_IdxRecno                    50
#define OP_Vacuum                      51
#define OP_If                          52
#define OP_Destroy                     53
#define OP_Clear                       54
#define OP_IdxGE                       55
#define OP_Divide                      79
#define OP_NewRecno                    56
#define OP_String8                     85
#define OP_Concat                      81
#define OP_FullKey                     57
#define OP_MakeRecord                  61
#define OP_SetCookie                   62
#define OP_Prev                        63
#define OP_AggGet                      83
#define OP_SortPut                     86
#define OP_ContextPush                 87
#define OP_ListWrite                   88
#define OP_DropTrigger                 89
#define OP_IdxGT                       90
#define OP_IdxColumn                   91
#define OP_AggNext                     92
#define OP_And                         59
#define OP_Return                      93
#define OP_OpenWrite                   94
#define OP_PutStrKey                   95
#define OP_Integer                     96
#define OP_Transaction                 97
#define OP_CollSeq                     98
#define OP_KeyAsData                   99
#define OP_ContextPop                  100
#define OP_ShiftRight                  75
#define OP_CreateTable                 101
#define OP_AddImm                      102
#define OP_IdxIsNull                   103
#define OP_IsUnique                    104
#define OP_DropTable                   105
#define OP_ListRead                    106
#define OP_AggInit                     107
#define OP_Noop                        108
#define OP_IdxPut                      109
#define OP_RowKey                      110
#define OP_OpenTemp                    111
#define OP_Delete                      112
#define OP_Subtract                    77
#define OP_MemIncr                     113
#define OP_Blob                        114
#define OP_Goto                        115
#define OP_Negative                    82
#define OP_ParseSchema                 116
#define OP_Eq                          67
#define OP_Pop                         117
#define OP_Le                          69
#define OP_ListReset                   118
#define OP_VerifyCookie                119
#define OP_Column                      120
#define OP_OpenRead                    121
#define OP_ResetCount                  124
