files:
  - source: /Localizations/en.xliff
    translation: /Localizations/%osx_locale%.xliff
    languages_mapping:
      osx_locale:
        pt-BR: pt-BR
  - source: /Vienna/Resources/Base.lproj/Localizable.stringsdict
    translation: /Vienna/Resources/%osx_locale%.lproj/Localizable.stringsdict
    languages_mapping:
      osx_locale:
        pt-BR: pt-BR
